using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PortalGovi.Models.Invoices

{
    // Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
    public class AddressExtension
    {
        public string ShipToStreet { get; set; }
        public object ShipToStreetNo { get; set; }
        public string ShipToBlock { get; set; }
        public string ShipToBuilding { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToZipCode { get; set; }
        public string ShipToCounty { get; set; }
        public string ShipToState { get; set; }
        public string ShipToCountry { get; set; }
        public object ShipToAddressType { get; set; }
        public string BillToStreet { get; set; }
        public object BillToStreetNo { get; set; }
        public string BillToBlock { get; set; }
        public string BillToBuilding { get; set; }
        public string BillToCity { get; set; }
        public string BillToZipCode { get; set; }
        public string BillToCounty { get; set; }
        public string BillToState { get; set; }
        public string BillToCountry { get; set; }
        public object BillToAddressType { get; set; }
        public object ShipToGlobalLocationNumber { get; set; }
        public object BillToGlobalLocationNumber { get; set; }
        public object ShipToAddress2 { get; set; }
        public object ShipToAddress3 { get; set; }
        public object BillToAddress2 { get; set; }
        public object BillToAddress3 { get; set; }
        public object PlaceOfSupply { get; set; }
        public object PurchasePlaceOfSupply { get; set; }
        public int DocEntry { get; set; }
        public object GoodsIssuePlaceBP { get; set; }
        public object GoodsIssuePlaceCNPJ { get; set; }
        public object GoodsIssuePlaceCPF { get; set; }
        public object GoodsIssuePlaceStreet { get; set; }
        public object GoodsIssuePlaceStreetNo { get; set; }
        public object GoodsIssuePlaceBuilding { get; set; }
        public object GoodsIssuePlaceZip { get; set; }
        public object GoodsIssuePlaceBlock { get; set; }
        public object GoodsIssuePlaceCity { get; set; }
        public object GoodsIssuePlaceCounty { get; set; }
        public object GoodsIssuePlaceState { get; set; }
        public object GoodsIssuePlaceCountry { get; set; }
        public object GoodsIssuePlacePhone { get; set; }
        public object GoodsIssuePlaceEMail { get; set; }
        public object GoodsIssuePlaceDepartureDate { get; set; }
        public object DeliveryPlaceBP { get; set; }
        public object DeliveryPlaceCNPJ { get; set; }
        public object DeliveryPlaceCPF { get; set; }
        public object DeliveryPlaceStreet { get; set; }
        public object DeliveryPlaceStreetNo { get; set; }
        public object DeliveryPlaceBuilding { get; set; }
        public object DeliveryPlaceZip { get; set; }
        public object DeliveryPlaceBlock { get; set; }
        public object DeliveryPlaceCity { get; set; }
        public object DeliveryPlaceCounty { get; set; }
        public object DeliveryPlaceState { get; set; }
        public object DeliveryPlaceCountry { get; set; }
        public object DeliveryPlacePhone { get; set; }
        public object DeliveryPlaceEMail { get; set; }
        public object DeliveryPlaceDepartureDate { get; set; }
        public string U_ZONAS { get; set; }
        public string U_ZONAB { get; set; }
    }

    public class DocumentInstallment
    {
        public DateTime DueDate { get; set; }
        public double Percentage { get; set; }
        public double Total { get; set; }
        public object LastDunningDate { get; set; }
        public int DunningLevel { get; set; }
        public double TotalFC { get; set; }
        public int InstallmentId { get; set; }
        public string PaymentOrdered { get; set; }
    }

    public class DocumentLine
    {
        public int LineNum { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public double Quantity { get; set; }
        public object ShipDate { get; set; }
        public double Price { get; set; }
        public double PriceAfterVAT { get; set; }
        public string Currency { get; set; }
        public double Rate { get; set; }
        public double DiscountPercent { get; set; }
        public object VendorNum { get; set; }
        public object SerialNum { get; set; }
        public string WarehouseCode { get; set; }
        public int SalesPersonCode { get; set; }
        public double CommisionPercent { get; set; }
        public string TreeType { get; set; }
        public string AccountCode { get; set; }
        public string UseBaseUnits { get; set; }
        public object SupplierCatNum { get; set; }
        public object CostingCode { get; set; }
        public object ProjectCode { get; set; }
        public object BarCode { get; set; }
        public object VatGroup { get; set; }
        public double Height1 { get; set; }
        public object Hight1Unit { get; set; }
        public double Height2 { get; set; }
        public object Height2Unit { get; set; }
        public double Lengh1 { get; set; }
        public object Lengh1Unit { get; set; }
        public double Lengh2 { get; set; }
        public object Lengh2Unit { get; set; }
        public double Weight1 { get; set; }
        public object Weight1Unit { get; set; }
        public double Weight2 { get; set; }
        public object Weight2Unit { get; set; }
        public double Factor1 { get; set; }
        public double Factor2 { get; set; }
        public double Factor3 { get; set; }
        public double Factor4 { get; set; }
        public int BaseType { get; set; }
        public object BaseEntry { get; set; }
        public object BaseLine { get; set; }
        public double Volume { get; set; }
        public int VolumeUnit { get; set; }
        public double Width1 { get; set; }
        public object Width1Unit { get; set; }
        public double Width2 { get; set; }
        public object Width2Unit { get; set; }
        public string Address { get; set; }
        public string TaxCode { get; set; }
        public string TaxType { get; set; }
        public string TaxLiable { get; set; }
        public string PickStatus { get; set; }
        public double PickQuantity { get; set; }
        public object PickListIdNumber { get; set; }
        public object OriginalItem { get; set; }
        public object BackOrder { get; set; }
        public object FreeText { get; set; }
        public int ShippingMethod { get; set; }
        public object POTargetNum { get; set; }
        public object POTargetEntry { get; set; }
        public object POTargetRowNum { get; set; }
        public string CorrectionInvoiceItem { get; set; }
        public double CorrInvAmountToStock { get; set; }
        public double CorrInvAmountToDiffAcct { get; set; }
        public double AppliedTax { get; set; }
        public double AppliedTaxFC { get; set; }
        public double AppliedTaxSC { get; set; }
        public string WTLiable { get; set; }
        public string DeferredTax { get; set; }
        public double EqualizationTaxPercent { get; set; }
        public double TotalEqualizationTax { get; set; }
        public double TotalEqualizationTaxFC { get; set; }
        public double TotalEqualizationTaxSC { get; set; }
        public double NetTaxAmount { get; set; }
        public double NetTaxAmountFC { get; set; }
        public double NetTaxAmountSC { get; set; }
        public object MeasureUnit { get; set; }
        public double UnitsOfMeasurment { get; set; }
        public double LineTotal { get; set; }
        public double TaxPercentagePerRow { get; set; }
        public double TaxTotal { get; set; }
        public string ConsumerSalesForecast { get; set; }
        public double ExciseAmount { get; set; }
        public double TaxPerUnit { get; set; }
        public double TotalInclTax { get; set; }
        public object CountryOrg { get; set; }
        public object SWW { get; set; }
        public object TransactionType { get; set; }
        public string DistributeExpense { get; set; }
        public double RowTotalFC { get; set; }
        public double RowTotalSC { get; set; }
        public double LastBuyInmPrice { get; set; }
        public double LastBuyDistributeSumFc { get; set; }
        public double LastBuyDistributeSumSc { get; set; }
        public double LastBuyDistributeSum { get; set; }
        public double StockDistributesumForeign { get; set; }
        public double StockDistributesumSystem { get; set; }
        public double StockDistributesum { get; set; }
        public double StockInmPrice { get; set; }
        public string PickStatusEx { get; set; }
        public double TaxBeforeDPM { get; set; }
        public double TaxBeforeDPMFC { get; set; }
        public double TaxBeforeDPMSC { get; set; }
        public object CFOPCode { get; set; }
        public object CSTCode { get; set; }
        public object Usage { get; set; }
        public string TaxOnly { get; set; }
        public int VisualOrder { get; set; }
        public double BaseOpenQuantity { get; set; }
        public double UnitPrice { get; set; }
        public string LineStatus { get; set; }
        public double PackageQuantity { get; set; }
        public object Text { get; set; }
        public string LineType { get; set; }
        public object COGSCostingCode { get; set; }
        public string COGSAccountCode { get; set; }
        public string ChangeAssemlyBoMWarehouse { get; set; }
        public double GrossBuyPrice { get; set; }
        public int GrossBase { get; set; }
        public double GrossProfitTotalBasePrice { get; set; }
        public object CostingCode2 { get; set; }
        public object CostingCode3 { get; set; }
        public object CostingCode4 { get; set; }
        public object CostingCode5 { get; set; }
        public object ItemDetails { get; set; }
        public object LocationCode { get; set; }
        public DateTime ActualDeliveryDate { get; set; }
        public double RemainingOpenQuantity { get; set; }
        public double OpenAmount { get; set; }
        public double OpenAmountFC { get; set; }
        public double OpenAmountSC { get; set; }
        public object ExLineNo { get; set; }
        public object RequiredDate { get; set; }
        public double RequiredQuantity { get; set; }
        public object COGSCostingCode2 { get; set; }
        public object COGSCostingCode3 { get; set; }
        public object COGSCostingCode4 { get; set; }
        public object COGSCostingCode5 { get; set; }
        public object CSTforIPI { get; set; }
        public object CSTforPIS { get; set; }
        public object CSTforCOFINS { get; set; }
        public object CreditOriginCode { get; set; }
        public string WithoutInventoryMovement { get; set; }
        public object AgreementNo { get; set; }
        public object AgreementRowNumber { get; set; }
        public object ActualBaseEntry { get; set; }
        public object ActualBaseLine { get; set; }
        public int DocEntry { get; set; }
        public double Surpluses { get; set; }
        public double DefectAndBreakup { get; set; }
        public double Shortages { get; set; }
        public string ConsiderQuantity { get; set; }
        public string PartialRetirement { get; set; }
        public double RetirementQuantity { get; set; }
        public double RetirementAPC { get; set; }
        public string ThirdParty { get; set; }
        public object PoNum { get; set; }
        public object PoItmNum { get; set; }
        public object ExpenseType { get; set; }
        public object ReceiptNumber { get; set; }
        public object ExpenseOperationType { get; set; }
        public object FederalTaxID { get; set; }
        public double GrossProfit { get; set; }
        public double GrossProfitFC { get; set; }
        public double GrossProfitSC { get; set; }
        public string PriceSource { get; set; }
        public object StgSeqNum { get; set; }
        public object StgEntry { get; set; }
        public object StgDesc { get; set; }
        public int UoMEntry { get; set; }
        public string UoMCode { get; set; }
        public double InventoryQuantity { get; set; }
        public double RemainingOpenInventoryQuantity { get; set; }
        public object ParentLineNum { get; set; }
        public int Incoterms { get; set; }
        public int TransportMode { get; set; }
        public object NatureOfTransaction { get; set; }
        public object DestinationCountryForImport { get; set; }
        public object DestinationRegionForImport { get; set; }
        public object OriginCountryForExport { get; set; }
        public object OriginRegionForExport { get; set; }
        public string ItemType { get; set; }
        public string ChangeInventoryQuantityIndependently { get; set; }
        public string FreeOfChargeBP { get; set; }
        public object SACEntry { get; set; }
        public object HSNEntry { get; set; }
        public double GrossPrice { get; set; }
        public double GrossTotal { get; set; }
        public double GrossTotalFC { get; set; }
        public double GrossTotalSC { get; set; }
        public int NCMCode { get; set; }
        public object NVECode { get; set; }
        public string IndEscala { get; set; }
        public double CtrSealQty { get; set; }
        public object CNJPMan { get; set; }
        public object CESTCode { get; set; }
        public object UFFiscalBenefitCode { get; set; }
        public string ReverseCharge { get; set; }
        public string ShipToCode { get; set; }
        public string ShipToDescription { get; set; }
        public double ExternalCalcTaxRate { get; set; }
        public double ExternalCalcTaxAmount { get; set; }
        public double ExternalCalcTaxAmountFC { get; set; }
        public double ExternalCalcTaxAmountSC { get; set; }
        public object StandardItemIdentification { get; set; }
        public object CommodityClassification { get; set; }
        public object UnencumberedReason { get; set; }
        public string CUSplit { get; set; }
        public object ListNum { get; set; }
        public object U_IdMarca { get; set; }
        public object U_DescrMarca { get; set; }
        public object U_ClaveUnidad { get; set; }
        public object U_SYD { get; set; }
        public object U_OEM { get; set; }
        public object U_DocEntryD { get; set; }
        public object U_NumPedimento { get; set; }
        public object U_DesctoManual { get; set; }
        public object U_Ubicacion { get; set; }
        public object U_Equiv0Syd { get; set; }
        public object U_Transito { get; set; }
        public object U_Cuarentena { get; set; }
        public object U_Proveedor { get; set; }
        public object U_Factura { get; set; }
        public object U_Marca { get; set; }
        public object U_Arancel { get; set; }
        public object U_UnidadAduana { get; set; }
        public object U_CantidadAduana { get; set; }
        public string U_B1SYS_SubjToTax { get; set; }
        public List<LineTaxJurisdiction> LineTaxJurisdictions { get; set; }
        public List<object> ExportProcesses { get; set; }
        public List<object> EBooksDetails { get; set; }
        public List<object> DocumentLineAdditionalExpenses { get; set; }
        public List<object> WithholdingTaxLines { get; set; }
        public List<object> SerialNumbers { get; set; }
        public List<object> BatchNumbers { get; set; }
        public List<object> CCDNumbers { get; set; }
        public List<object> DocumentLinesBinAllocations { get; set; }
    }

    public class ElectronicProtocol
    {
        public string ProtocolCode { get; set; }
        public string GenerationType { get; set; }
        public int MappingID { get; set; }
        public string TestingMode { get; set; }
        public object Confirmation { get; set; }
        public object EDocType { get; set; }
        public object EBooksRelevant { get; set; }
        public object EBooksMARK { get; set; }
        public object EBooksMARKofNegative { get; set; }
        public object EBooksInvoiceType { get; set; }
        public object EBooksInvoiceTypeofNegative { get; set; }
        public object EBillingIRN { get; set; }
        public object EETPKP { get; set; }
        public object EETBKP { get; set; }
        public string SignatureInputMessage { get; set; }
        public string SignatureDigest { get; set; }
        public object FechaTimbrado { get; set; }
        public string SelloSAT { get; set; }
        public string PaymentMethod { get; set; }
        public object RfcProvCertif { get; set; }
        public object NoCertificadoSAT { get; set; }
        public object FPASequenceNumber { get; set; }
        public object FPASendDateSDI { get; set; }
        public object FPAProgressivo { get; set; }
        public string ProtocolDescription { get; set; }
        public string CFDiExport { get; set; }
        public object CFDiCancellationReason { get; set; }
        public object CFDiCancellationResponse { get; set; }
        public object CFDiCancellationReference { get; set; }
        public List<object> RelatedDocuments { get; set; }
    }

    public class EWayBillDetails
    {
    }

    public class LineTaxJurisdiction
    {
        public string JurisdictionCode { get; set; }
        public int JurisdictionType { get; set; }
        public double TaxAmount { get; set; }
        public double TaxAmountSC { get; set; }
        public double TaxAmountFC { get; set; }
        public double TaxRate { get; set; }
        public int DocEntry { get; set; }
        public int LineNumber { get; set; }
        public int RowSequence { get; set; }
        public object ExternalCalcTaxRate { get; set; }
        public object ExternalCalcTaxAmount { get; set; }
        public object ExternalCalcTaxAmountFC { get; set; }
        public object ExternalCalcTaxAmountSC { get; set; }
    }

    public class Root
    {
        [JsonProperty("odata.metadata")]
        public string odatametadata { get; set; }

        [JsonProperty("odata.etag")]
        public string odataetag { get; set; }
        public int DocEntry { get; set; }
        public int DocNum { get; set; }
        public string DocType { get; set; }
        public string HandWritten { get; set; }
        public string Printed { get; set; }
        public DateTime DocDate { get; set; }
        public DateTime DocDueDate { get; set; }
        public string CardCode { get; set; }
        public string CardName { get; set; }
        public string Address { get; set; }
        public object NumAtCard { get; set; }
        public double DocTotal { get; set; }
        public object AttachmentEntry { get; set; }
        public string DocCurrency { get; set; }
        public double DocRate { get; set; }
        public string Reference1 { get; set; }
        public object Reference2 { get; set; }
        public string Comments { get; set; }
        public string JournalMemo { get; set; }
        public int PaymentGroupCode { get; set; }
        public string DocTime { get; set; }
        public int SalesPersonCode { get; set; }
        public int TransportationCode { get; set; }
        public string Confirmed { get; set; }
        public object ImportFileNum { get; set; }
        public string SummeryType { get; set; }
        public int ContactPersonCode { get; set; }
        public string ShowSCN { get; set; }
        public int Series { get; set; }
        public DateTime TaxDate { get; set; }
        public string PartialSupply { get; set; }
        public string DocObjectCode { get; set; }
        public string ShipToCode { get; set; }
        public object Indicator { get; set; }
        public string FederalTaxID { get; set; }
        public double DiscountPercent { get; set; }
        public object PaymentReference { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime UpdateDate { get; set; }
        public int FinancialPeriod { get; set; }
        public int UserSign { get; set; }
        public int TransNum { get; set; }
        public double VatSum { get; set; }
        public double VatSumSys { get; set; }
        public double VatSumFc { get; set; }
        public string NetProcedure { get; set; }
        public double DocTotalFc { get; set; }
        public double DocTotalSys { get; set; }
        public object Form1099 { get; set; }
        public object Box1099 { get; set; }
        public string RevisionPo { get; set; }
        public object RequriedDate { get; set; }
        public object CancelDate { get; set; }
        public string BlockDunning { get; set; }
        public string Submitted { get; set; }
        public int Segment { get; set; }
        public string PickStatus { get; set; }
        public string Pick { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentBlock { get; set; }
        public object PaymentBlockEntry { get; set; }
        public object CentralBankIndicator { get; set; }
        public string MaximumCashDiscount { get; set; }
        public string Reserve { get; set; }
        public object Project { get; set; }
        public object ExemptionValidityDateFrom { get; set; }
        public object ExemptionValidityDateTo { get; set; }
        public string WareHouseUpdateType { get; set; }
        public string Rounding { get; set; }
        public object ExternalCorrectedDocNum { get; set; }
        public object InternalCorrectedDocNum { get; set; }
        public object NextCorrectingDocument { get; set; }
        public string DeferredTax { get; set; }
        public object TaxExemptionLetterNum { get; set; }
        public double WTApplied { get; set; }
        public double WTAppliedFC { get; set; }
        public string BillOfExchangeReserved { get; set; }
        public object AgentCode { get; set; }
        public double WTAppliedSC { get; set; }
        public double TotalEqualizationTax { get; set; }
        public double TotalEqualizationTaxFC { get; set; }
        public double TotalEqualizationTaxSC { get; set; }
        public int NumberOfInstallments { get; set; }
        public string ApplyTaxOnFirstInstallment { get; set; }
        public double WTNonSubjectAmount { get; set; }
        public double WTNonSubjectAmountSC { get; set; }
        public double WTNonSubjectAmountFC { get; set; }
        public double WTExemptedAmount { get; set; }
        public double WTExemptedAmountSC { get; set; }
        public double WTExemptedAmountFC { get; set; }
        public double BaseAmount { get; set; }
        public double BaseAmountSC { get; set; }
        public double BaseAmountFC { get; set; }
        public double WTAmount { get; set; }
        public double WTAmountSC { get; set; }
        public double WTAmountFC { get; set; }
        public object VatDate { get; set; }
        public object DocumentsOwner { get; set; }
        public object FolioPrefixString { get; set; }
        public object FolioNumber { get; set; }
        public string DocumentSubType { get; set; }
        public object BPChannelCode { get; set; }
        public object BPChannelContact { get; set; }
        public string Address2 { get; set; }
        public string DocumentStatus { get; set; }
        public string PeriodIndicator { get; set; }
        public string PayToCode { get; set; }
        public object ManualNumber { get; set; }
        public string UseShpdGoodsAct { get; set; }
        public string IsPayToBank { get; set; }
        public object PayToBankCountry { get; set; }
        public object PayToBankCode { get; set; }
        public object PayToBankAccountNo { get; set; }
        public object PayToBankBranch { get; set; }
        public int BPL_IDAssignedToInvoice { get; set; }
        public double DownPayment { get; set; }
        public string ReserveInvoice { get; set; }
        public int LanguageCode { get; set; }
        public object TrackingNumber { get; set; }
        public object PickRemark { get; set; }
        public object ClosingDate { get; set; }
        public object SequenceCode { get; set; }
        public object SequenceSerial { get; set; }
        public object SeriesString { get; set; }
        public object SubSeriesString { get; set; }
        public string SequenceModel { get; set; }
        public string UseCorrectionVATGroup { get; set; }
        public double TotalDiscount { get; set; }
        public double DownPaymentAmount { get; set; }
        public double DownPaymentPercentage { get; set; }
        public string DownPaymentType { get; set; }
        public double DownPaymentAmountSC { get; set; }
        public double DownPaymentAmountFC { get; set; }
        public double VatPercent { get; set; }
        public double ServiceGrossProfitPercent { get; set; }
        public object OpeningRemarks { get; set; }
        public object ClosingRemarks { get; set; }
        public double RoundingDiffAmount { get; set; }
        public double RoundingDiffAmountFC { get; set; }
        public double RoundingDiffAmountSC { get; set; }
        public string Cancelled { get; set; }
        public object SignatureInputMessage { get; set; }
        public object SignatureDigest { get; set; }
        public object CertificationNumber { get; set; }
        public object PrivateKeyVersion { get; set; }
        public string ControlAccount { get; set; }
        public string InsuranceOperation347 { get; set; }
        public string ArchiveNonremovableSalesQuotation { get; set; }
        public object GTSChecker { get; set; }
        public object GTSPayee { get; set; }
        public int ExtraMonth { get; set; }
        public int ExtraDays { get; set; }
        public int CashDiscountDateOffset { get; set; }
        public string StartFrom { get; set; }
        public string NTSApproved { get; set; }
        public object ETaxWebSite { get; set; }
        public object ETaxNumber { get; set; }
        public object NTSApprovedNumber { get; set; }
        public string EDocGenerationType { get; set; }
        public object EDocSeries { get; set; }
        public object EDocNum { get; set; }
        public object EDocExportFormat { get; set; }
        public string EDocStatus { get; set; }
        public object EDocErrorCode { get; set; }
        public object EDocErrorMessage { get; set; }
        public string DownPaymentStatus { get; set; }
        public object GroupSeries { get; set; }
        public object GroupNumber { get; set; }
        public string GroupHandWritten { get; set; }
        public object ReopenOriginalDocument { get; set; }
        public object ReopenManuallyClosedOrCanceledDocument { get; set; }
        public string CreateOnlineQuotation { get; set; }
        public object POSEquipmentNumber { get; set; }
        public object POSManufacturerSerialNumber { get; set; }
        public object POSCashierNumber { get; set; }
        public string ApplyCurrentVATRatesForDownPaymentsToDraw { get; set; }
        public string ClosingOption { get; set; }
        public object SpecifiedClosingDate { get; set; }
        public string OpenForLandedCosts { get; set; }
        public string AuthorizationStatus { get; set; }
        public double TotalDiscountFC { get; set; }
        public double TotalDiscountSC { get; set; }
        public string RelevantToGTS { get; set; }
        public string BPLName { get; set; }
        public string VATRegNum { get; set; }
        public object AnnualInvoiceDeclarationReference { get; set; }
        public object Supplier { get; set; }
        public object Releaser { get; set; }
        public object Receiver { get; set; }
        public object BlanketAgreementNumber { get; set; }
        public string IsAlteration { get; set; }
        public string CancelStatus { get; set; }
        public DateTime AssetValueDate { get; set; }
        public string InvoicePayment { get; set; }
        public string DocumentDelivery { get; set; }
        public object AuthorizationCode { get; set; }
        public object StartDeliveryDate { get; set; }
        public object StartDeliveryTime { get; set; }
        public object EndDeliveryDate { get; set; }
        public object EndDeliveryTime { get; set; }
        public object VehiclePlate { get; set; }
        public object ATDocumentType { get; set; }
        public object ElecCommStatus { get; set; }
        public object ElecCommMessage { get; set; }
        public string ReuseDocumentNum { get; set; }
        public string ReuseNotaFiscalNum { get; set; }
        public string PrintSEPADirect { get; set; }
        public object FiscalDocNum { get; set; }
        public object POSDailySummaryNo { get; set; }
        public object POSReceiptNo { get; set; }
        public object PointOfIssueCode { get; set; }
        public object Letter { get; set; }
        public object FolioNumberFrom { get; set; }
        public object FolioNumberTo { get; set; }
        public string InterimType { get; set; }
        public int RelatedType { get; set; }
        public object RelatedEntry { get; set; }
        public object SAPPassport { get; set; }
        public object DocumentTaxID { get; set; }
        public object DateOfReportingControlStatementVAT { get; set; }
        public object ReportingSectionControlStatementVAT { get; set; }
        public string ExcludeFromTaxReportControlStatementVAT { get; set; }
        public object POS_CashRegister { get; set; }
        public string UpdateTime { get; set; }
        public object CreateQRCodeFrom { get; set; }
        public object PriceMode { get; set; }
        public string Revision { get; set; }
        public object OriginalRefNo { get; set; }
        public object OriginalRefDate { get; set; }
        public object GSTTransactionType { get; set; }
        public object OriginalCreditOrDebitNo { get; set; }
        public object OriginalCreditOrDebitDate { get; set; }
        public object ECommerceOperator { get; set; }
        public object ECommerceGSTIN { get; set; }
        public string ShipFrom { get; set; }
        public string CommissionTrade { get; set; }
        public string CommissionTradeReturn { get; set; }
        public string UseBillToAddrToDetermineTax { get; set; }
        public int IssuingReason { get; set; }
        public object Cig { get; set; }
        public object Cup { get; set; }
        public string EDocType { get; set; }
        public string FCEAsPaymentMeans { get; set; }
        public double PaidToDate { get; set; }
        public double PaidToDateFC { get; set; }
        public double PaidToDateSys { get; set; }
        public int BaseType { get; set; }
        public object BaseEntry { get; set; }
        public object FatherCard { get; set; }
        public string FatherType { get; set; }
        public object ShipState { get; set; }
        public object ShipPlace { get; set; }
        public object CustOffice { get; set; }
        public object FCI { get; set; }
        public object AddLegIn { get; set; }
        public object LegTextF { get; set; }
        public object DANFELgTxt { get; set; }
        public string IndFinal { get; set; }
        public int DataVersion { get; set; }
        public object LastPageFolioNumber { get; set; }
        public string InventoryStatus { get; set; }
        public string PlasticPackagingTaxRelevant { get; set; }
        public object U_SaldoSN { get; set; }
        public object U_Chofer { get; set; }
        public object U_Fuente { get; set; }
        public object U_Sucursal { get; set; }
        public object U_ALMACEN { get; set; }
        public object U_SO1_01SUCURSAL { get; set; }
        public object U_RUTA { get; set; }
        public object U_Consignado { get; set; }
        public object U_FolioPedidoWeb { get; set; }
        public object U_CondicionesPago { get; set; }
        public string U_MetodoPago { get; set; }
        public object U_UsuarioPortal { get; set; }
        public object U_OrdenCompraLote { get; set; }
        public object U_TRANSPORTISTAS { get; set; }
        public object U_TIPODETRANSPORTE { get; set; }
        public object U_CONCNCGO { get; set; }
        public object U_CONCNCRE { get; set; }
        public string U_PRIORIDAD { get; set; }
        public string U_LugarExpedicion { get; set; }
        public object U_VEHICULO { get; set; }
        public object U_AduanaDesp { get; set; }
        public object U_AnioValidacion { get; set; }
        public object U_FechaEmbarque { get; set; }
        public string U_CREADOHH { get; set; }
        public object U_NumPedimento { get; set; }
        public object U_B1SYS_Confirm { get; set; }
        public string U_B1SYS_MainUsage { get; set; }
        public object U_UDF_UUID { get; set; }
        public object U_FolioReabasto { get; set; }
        public string U_Relevancia { get; set; }
        public object U_CONCDEVOL { get; set; }
        public object U_InvoiceSPO { get; set; }
        public object U_Transito { get; set; }
        public string U_CREADOOC { get; set; }
        public object U_NumCta { get; set; }
        public object U_NombreCheque { get; set; }
        public object U_FechaDeposito { get; set; }
        public object U_FechaRebote { get; set; }
        public object U_FechaPago { get; set; }
        public object U_Banco { get; set; }
        public object U_Cheque { get; set; }
        public object U_Importe { get; set; }
        public object U_MotivodeRebote { get; set; }
        public object U_Comentario { get; set; }
        public object U_Email { get; set; }
        public object U_Vendedor { get; set; }
        public object U_EmailVendedor { get; set; }
        public object U_FolioCompras { get; set; }
        public object U_FechaCompromiso { get; set; }
        public object U_SaldoAnticipo { get; set; }
        public object U_DESCTODEV { get; set; }
        public double U_TransId { get; set; }
        public object U_CertificadoOrigen { get; set; }
        public object U_Subdivision { get; set; }
        public object U_Incoterm { get; set; }
        public object U_NumCertificadoOrigen { get; set; }
        public string U_Domiciliado { get; set; }
        public object U_Referencia { get; set; }
        public string U_EnviarCFDi { get; set; }
        public object U_B1SYS_CFDiPeriod { get; set; }
        public object U_B1SYS_CFDiMonths { get; set; }
        public object U_B1SYS_CFDiYear { get; set; }
        public List<object> Document_ApprovalRequests { get; set; }
        public List<DocumentLine> DocumentLines { get; set; }
        public EWayBillDetails EWayBillDetails { get; set; }
        public List<ElectronicProtocol> ElectronicProtocols { get; set; }
        public List<object> DocumentAdditionalExpenses { get; set; }
        public List<object> WithholdingTaxDataWTXCollection { get; set; }
        public List<object> WithholdingTaxDataCollection { get; set; }
        public List<object> DocumentPackages { get; set; }
        public List<object> DocumentSpecialLines { get; set; }
        public List<DocumentInstallment> DocumentInstallments { get; set; }
        public List<object> DownPaymentsToDraw { get; set; }
        public TaxExtension TaxExtension { get; set; }
        public AddressExtension AddressExtension { get; set; }
        public List<object> DocumentReferences { get; set; }
    }

    public class TaxExtension
    {
        public object TaxId0 { get; set; }
        public object TaxId1 { get; set; }
        public object TaxId2 { get; set; }
        public object TaxId3 { get; set; }
        public object TaxId4 { get; set; }
        public object TaxId5 { get; set; }
        public object TaxId6 { get; set; }
        public object TaxId7 { get; set; }
        public object TaxId8 { get; set; }
        public object TaxId9 { get; set; }
        public object State { get; set; }
        public object County { get; set; }
        public object Incoterms { get; set; }
        public object Vehicle { get; set; }
        public object VehicleState { get; set; }
        public object NFRef { get; set; }
        public object Carrier { get; set; }
        public object PackQuantity { get; set; }
        public object PackDescription { get; set; }
        public object Brand { get; set; }
        public object ShipUnitNo { get; set; }
        public double NetWeight { get; set; }
        public double GrossWeight { get; set; }
        public string StreetS { get; set; }
        public string BlockS { get; set; }
        public string BuildingS { get; set; }
        public string CityS { get; set; }
        public string ZipCodeS { get; set; }
        public string CountyS { get; set; }
        public string StateS { get; set; }
        public string CountryS { get; set; }
        public string StreetB { get; set; }
        public string BlockB { get; set; }
        public string BuildingB { get; set; }
        public string CityB { get; set; }
        public string ZipCodeB { get; set; }
        public string CountyB { get; set; }
        public string StateB { get; set; }
        public string CountryB { get; set; }
        public object ImportOrExport { get; set; }
        public object MainUsage { get; set; }
        public object GlobalLocationNumberS { get; set; }
        public object GlobalLocationNumberB { get; set; }
        public object TaxId12 { get; set; }
        public object TaxId13 { get; set; }
        public object BillOfEntryNo { get; set; }
        public object BillOfEntryDate { get; set; }
        public object OriginalBillOfEntryNo { get; set; }
        public object OriginalBillOfEntryDate { get; set; }
        public string ImportOrExportType { get; set; }
        public object PortCode { get; set; }
        public int DocEntry { get; set; }
        public double BoEValue { get; set; }
        public object ClaimRefund { get; set; }
        public object DifferentialOfTaxRate { get; set; }
        public object IsIGSTAccount { get; set; }
        public object TaxId14 { get; set; }
    }


}
